<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
        <base href="/meteo.local" />
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="css/master.css">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <script src="js/bootstrap.min.js" charset="utf-8"></script>
    <script src="js/ajaxmenu.js" charset="utf-8"></script>
    <script src="js/jquery-3.4.1.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="js/googlecharts.js"></script>
  </head>
  <body>
    <header class="menu">
      <nav class="navbar navbarMain navbar-expand-md" id="navbarMain">
        <div class="container-fluid">
          <a class="navbar-brand pl-5" href="home/idStanice-3710"><img class="mr-3" src="images/jmnet-logo.png" alt="" width="120">Meteo monitor</a>
          <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#MyTogglerNav" aria-controls="#MyTogglerNav"
           aria-label="Toggle Navigation"><span class="navbar-toggler-icon"></span></button>
           <section class="collapse navbar-collapse" id="MyTogglerNav">
             <div class="navbar-nav ml-auto">
             </div>
           </section>
           <select class="custom-select w-25" onchange="redir(this.value)">
             <option selected value="">Stanice</option>
             <?php while($row = ibase_fetch_object($seznamStanic)) : ?>
                  <option value="<?= $row->ID ?>"><?= $row->JMENO ?></option>
             <?php endwhile ?>
           </select>
        </div>

      </div>
      </nav>

    </header>

    <div style="position:absolute;top:0;right:0;">
  <?php foreach($zpravy as $zpr) : ?>
  <div class="toast bg-dark" style="position: absolute; top: 8vh; right: 10px;" data-autohide='false'>
    <div class="toast-header">
      <strong class="mr-auto">Upozornění</strong>
      <small class="mx-2"><?= date('G:i') ?></small>
      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="toast-body" style="color:#fff;">
      <?= $zpr ?>
    </div>
  </div>
  <?php endforeach ?>
    </div>

    <article class="pb-5">
      <?php $this->controller->showView(); ?>
    </article>
    <footer class="bg-dark text-center text-light">
        <h1>Made with love</h1>
    </footer>
    <script>
      function redir(str) {
        window.location.replace("home/idStanice-" + str);
      }
    </script>
  </body>
</html>
