<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
        <base href="/meteo.local" />
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="css/master.css">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <script src="js/bootstrap.min.js" charset="utf-8"></script>
    <script src="js/ajaxmenu.js" charset="utf-8"></script>
    <script src="js/jquery-3.4.1.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="js/googlecharts.js"></script>
  </head>
  <body>
    <header class="menu">
      <nav class="navbar navbarMain navbar-expand-md" id="navbarMain">
        <div class="container-fluid">
          <a class="navbar-brand pl-5" href="home/idStanice-3710"><img class="mr-3" src="images/jmnet-logo.png" alt="" width="120">Meteo monitor</a>
          <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#MyTogglerNav" aria-controls="#MyTogglerNav"
           aria-label="Toggle Navigation"><span class="navbar-toggler-icon"></span></button>
           <section class="collapse navbar-collapse" id="MyTogglerNav">
             <div class="navbar-nav ml-auto">
             </div>
           </section>
        </div>
      </nav>
    </header>

    <div style="position:absolute;top:0;right:0;">
  <?php foreach($zpravy as $zpr) : ?>
  <div class="toast bg-dark" style="position: absolute; top: 8vh; right: 10px;" data-autohide='false'>
    <div class="toast-header">
      <strong class="mr-auto">Upozornění</strong>
      <small class="mx-2"><?= date('G:i') ?></small>
      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="toast-body" style="color:#fff;">
      <?= $zpr ?>
    </div>
  </div>
  <?php endforeach ?>
    </div>
    
    <article class="pb-5">
      <?php $this->controller->showView(); ?>
    </article>
    <footer class="bg-dark text-center text-light">
        <h1>Made with love</h1>
        <div id="chart_div"></div>
    </footer>

      <script type="text/javascript">
  google.charts.load('current', {'packages':['line']});
  google.charts.setOnLoadCallback(drawChart);

  function drawChart() {

    google.charts.load('current', {packages: ['corechart', 'line']});
    google.charts.setOnLoadCallback(drawBasic);

    function drawBasic() {

          var data = new google.visualization.DataTable();
          data.addColumn('number', 'X');
          data.addColumn('number', 'Dogs');

          data.addRows([
            [0, 0],   [1, 10],  [2, 23],  [3, 17],  [4, 18],  [5, 9],
            [6, 11],  [7, 27],  [8, 33],  [9, 40],  [10, 32], [11, 35],
            [12, 30], [13, 40], [14, 42], [15, 47], [16, 44], [17, 48],
            [18, 52], [19, 54], [20, 42], [21, 55], [22, 56], [23, 57],
            [24, 60], [25, 50], [26, 52], [27, 51], [28, 49], [29, 53],
            [30, 55], [31, 60], [32, 61], [33, 59], [34, 62], [35, 65],
            [36, 62], [37, 58], [38, 55], [39, 61], [40, 64], [41, 65],
            [42, 63], [43, 66], [44, 67], [45, 69], [46, 69], [47, 70],
            [48, 72], [49, 68], [50, 66], [51, 65], [52, 67], [53, 70],
            [54, 71], [55, 72], [56, 73], [57, 75], [58, 70], [59, 68],
            [60, 64], [61, 60], [62, 65], [63, 67], [64, 68], [65, 69],
            [66, 70], [67, 72], [68, 75], [69, 80]
          ]);

          var options = {
            hAxis: {
              title: 'Time'
            },
            vAxis: {
              title: 'Popularity'
            }
          };

          var chart = new google.visualization.LineChart(document.getElementById('chart_div'));

          chart.draw(data, options);
        }
      }
      </script>

  </body>
</html>
