<section class="horniPanel d-flex justify-content-between p-5" id="horniPanelos">

</section>

  <div class="p-4 dolejsekWrapper">
    <section class="ajmenu w-75 mx-auto">
      <ul class="nav nav-pills nav-fill bg-dark">
  <li class="nav-item" onClick="clickAjHandler(`aktualne`)">
    <a class="nav-link pt-3 active">Aktuálně</a>
  </li>
  <li class="nav-item" onClick="clickAjHandler(`dennisouhrn`)">
    <a class="nav-link pt-3">Denní souhrny</a>
  </li>
  <li class="nav-item" onClick="clickAjHandler(`mesicnisouhrn`)">
    <a class="nav-link pt-3">Měsíční souhrny</a>
  </li>
  <li class="nav-item" onClick="clickAjHandler(`rocnisouhrn`)">
    <a class="nav-link pt-3">Roční souhrny</a>
  </li>
  </ul>
    <div id="ajoutput"></div>
    </section>
  </div>

  <script type="text/javascript">
  function checkData() {
  if (window.XMLHttpRequest) {
      xmlhttp = new XMLHttpRequest();
  } else {
      xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
  }
  xmlhttp.onreadystatechange = function() {
      if (this.readyState == 4 && this.status == 200) {
          document.getElementById('horniPanelos').innerHTML = this.responseText;
      }
    };
    xmlhttp.open("GET","models/ajaxchecker.php",true);
    xmlhttp.send();
  }
  checkData();
  setInterval('checkData()', 60000);

  </script>

  <script type="text/javascript">
  if (window.XMLHttpRequest) {
      xmlhttp = new XMLHttpRequest();
  } else {
      xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
  }
  xmlhttp.onreadystatechange = function() {
      if (this.readyState == 4 && this.status == 200) {
        if (document.getElementById("ajoutput").innerHTML = "") {
          document.getElementById("ajoutput").innerHTML = "<p><img src='images/loading.gif'></p>";
        }
          document.getElementById("ajoutput").innerHTML = this.responseText;
          //Graf aktualne 1.1
          google.charts.load('current', {'packages':['line']});
          google.charts.setOnLoadCallback(drawChart_Aktualne_1_1);
          function drawChart_Aktualne_1_1() {
          google.charts.load('current', {'packages':['line']});
          google.charts.setOnLoadCallback(drawBasic_Aktualne_1_1);
          function drawBasic_Aktualne_1_1() {
              var data = new google.visualization.DataTable();
              data.addColumn('number', 'čas');
              data.addColumn('number', 'Teplota');
              data.addColumn('number', 'Rychlost větru');
              data.addColumn('number', 'Rosný bod');

              data.addRows([
                  <?php while($dataGraf = ibase_fetch_object($getTimeAndTemp)) : ?>
                    <?=  $dataGraf->DATA ?>,
                  <?php endwhile ?>
              ]);

              var options = {
                'title': 'Posledních 24 hodin',
                'curveType': 'function',
                hAxis: {
                  title: 'Čas'
                },
                vAxis: {
                  title: 'Hodnota'
                }
              };
              var chart = new google.charts.Line(document.getElementById('chart_aktualne'));
              chart.draw(data, google.charts.Line.convertOptions(options));
            }
          }
          //Graf aktualne 1.1 KONEC

          //Graf aktualne 2.1
          google.charts.setOnLoadCallback(drawChart_Aktualne_2_1);
          function drawChart_Aktualne_2_1() {
          google.charts.load('current', {'packages':['line']});
          google.charts.setOnLoadCallback(drawBasic_Aktuale_2_1);
          function drawBasic_Aktuale_2_1() {
              var data = new google.visualization.DataTable();
              data.addColumn('number', 'čas');
              data.addColumn('number', 'vlhkost');

              data.addRows([
                <?php while($dataGraf = ibase_fetch_object($getHumidity)) : ?>
                  <?=  $dataGraf->DATA ?>,
                <?php endwhile ?>
              ]);

              var options = {
                'title':'Poslední 3 dny',
                hAxis: {
                  title: 'Čas'
                },
                vAxis: {
                  title: 'Hodnota'
                }
              };
              var chart = new google.charts.Line(document.getElementById('chart_aktualne1'));
              chart.draw(data, options);
            }
          }
          //Graf aktualne 2.1 KONEC

          //Graf 3 dny
          google.charts.setOnLoadCallback(drawChart_3Dny);
          function drawChart_3Dny() {
          google.charts.load('current', {'packages':['line']});
          google.charts.setOnLoadCallback(drawBasic3Dny);
          function drawBasic3Dny() {
              var data = new google.visualization.DataTable();
              data.addColumn('date', 'Datum');
              data.addColumn('number', 'Teplota');
              data.addColumn('number', 'Rychlost větru');
              data.addColumn('number', 'Rosný bod');

              data.addRows([
                <?php while($dG = ibase_fetch_object($getLast3DaysTimeTemp)) : ?>
                  [new Date(<?=$dG->ROK?>,<?=$dG->MESIC?>,<?=$dG->DEN?>,<?=$dG->HODINA?>,<?=$dG->MINUTA?>), <?=$dG->TEPLOTA?>,<?=$dG->RYCHLOST?>,<?=$dG->ROSNYBOD?>],
                <?php endwhile ?>
              ]);

              var options = {
                'title': 'Poslední 3 dny',
                'curveType': 'function',
                hAxis: {
                  title: 'Čas'
                },
                vAxis: {
                  title: 'Hodnota'
                }
              };
              var chart = new google.charts.Line(document.getElementById('chart_3dny'));
              chart.draw(data, google.charts.Line.convertOptions(options));
            }
          }

      }
  };

  xmlhttp.open("GET","views/home/aktualne.phtml",true);
  xmlhttp.send();

  function clickAjHandler(str) {
        if (window.XMLHttpRequest) {
            xmlhttp = new XMLHttpRequest();
        } else {
            xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
        }
        xmlhttp.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
              if (document.getElementById("ajoutput").innerHTML != this.responseText) {
                document.getElementById("ajoutput").innerHTML = "<p><img src='images/loading.gif'></p>";
              }
                document.getElementById("ajoutput").innerHTML = this.responseText;
                if (str == "aktualne") {
                  //Graf aktualne 1.2
                  google.charts.load('current', {'packages':['line']});
                  google.charts.setOnLoadCallback(drawChart_Aktualne_1_2);
                  function drawChart_Aktualne_1_2() {
                  google.charts.load('current', {'packages':['line']});
                  google.charts.setOnLoadCallback(drawBasic_Aktualne_1_2);
                  function drawBasic_Aktualne_1_2() {
                      var data = new google.visualization.DataTable();
                      data.addColumn('number', 'čas');
                      data.addColumn('number', 'Teplota');
                      data.addColumn('number', 'Rychlost větru');
                      data.addColumn('number', 'Rosný bod');

                      data.addRows([
                        <?php while($dataGraf = ibase_fetch_object($getTimeAndTemp2)) : ?>
                          <?=  $dataGraf->DATA ?>,
                        <?php endwhile ?>
                      ]);

                      var options = {
                        'title': 'Posledních 24 hodin',
                        'curveType': 'function',
                        hAxis: {
                          title: 'Čas'
                        },
                        vAxis: {
                          title: 'Hodnota'
                        }
                      };
                      var chart = new google.charts.Line(document.getElementById('chart_aktualne'));
                      chart.draw(data, google.charts.Line.convertOptions(options));
                    }
                  }
                  //Graf aktualne 1.2 KONEC

                  google.charts.setOnLoadCallback(drawChart_Aktualne_2_2);
                  function drawChart_Aktualne_2_2() {
                  google.charts.load('current', {'packages':['line']});
                  google.charts.setOnLoadCallback(drawBasic_Aktualne_2_2);
                  function drawBasic_Aktualne_2_2() {
                      var data = new google.visualization.DataTable();
                      data.addColumn('number', 'čas');
                      data.addColumn('number', 'teplota');

                      data.addRows([
                        <?php while($dataGraf = ibase_fetch_object($getHumidity2)) : ?>
                          <?=  $dataGraf->DATA ?>,
                        <?php endwhile ?>
                      ]);

                      var options = {
                        'title' :'Vlhkost',
                        hAxis: {
                          title: 'Čas'
                        },
                        vAxis: {
                          title: 'Hodnota'
                        }
                      };
                      var chart = new google.charts.Line(document.getElementById('chart_aktualne1'));
                      chart.draw(data, options);
                    }
                  }
                  //Graf aktualne 2.2 KONEC
                  //Graf 3dny
                  google.charts.setOnLoadCallback(drawChart_3Dny);
                  function drawChart_3Dny() {
                  google.charts.load('current', {'packages':['line']});
                  google.charts.setOnLoadCallback(drawBasic3Dny);
                  function drawBasic3Dny() {
                      var data = new google.visualization.DataTable();
                      data.addColumn('date', 'Datum');
                      data.addColumn('number', 'Teplota');
                      data.addColumn('number', 'Rychlost větru');
                      data.addColumn('number', 'Rosný bod');

                      data.addRows([
                        <?php while($dG = ibase_fetch_object($getLast3DaysTimeTemp)) : ?>
                          [new Date(<?=$dG->ROK?>,<?=$dG->MESIC?>,<?=$dG->DEN?>,<?=$dG->HODINA?>,<?=$dG->MINUTA?>), <?=$dG->TEPLOTA?>,<?=$dG->RYCHLOST?>,<?=$dG->ROSNYBOD?>],
                        <?php endwhile ?>
                      ]);

                      var options = {
                        'title': 'Poslední 3 dny',
                        'curveType': 'function',
                        hAxis: {
                          title: 'Čas'
                        },
                        vAxis: {
                          title: 'Hodnota'
                        }
                      };
                      var chart = new google.charts.Line(document.getElementById('chart_3dny'));
                      chart.draw(data, google.charts.Line.convertOptions(options));
                    }
                  }
                  //Graf 3dny konec
                } else if (str == "dennisouhrn") {

                  //Graf denni 1
                  google.charts.load('current', {'packages':['line']});
                  google.charts.setOnLoadCallback(drawChart4);
                  function drawChart4() {
                  google.charts.load('current', {'packages':['line']});
                  google.charts.setOnLoadCallback(drawBasic4);

                  function drawBasic4() {
                      var data = new google.visualization.DataTable();
                      data.addColumn('number', 'čas');
                      data.addColumn('number', 'teplota');

                      data.addRows([
                          [0,1],[0,2]
                    ]);

                      var options = {
                        'title':'Denní souhrn',
                        hAxis: {
                          title: 'Čas'
                        },
                        vAxis: {
                          title: 'Teplota'
                        }
                      };
                      var chart = new google.charts.Line(document.getElementById('chart_denni'));
                      chart.draw(data, options);
                    }
                  }
                  //Graf denni 1 KONEC
                } else if (str == "mesicnisouhrn") {
                  //Graf mesicni 1
                  google.charts.load('current', {'packages':['line']});
                  google.charts.setOnLoadCallback(drawChart5);
                  function drawChart5() {
                  google.charts.load('current', {'packages':['line']});
                  google.charts.setOnLoadCallback(drawBasic5);

                  function drawBasic5() {
                      var data = new google.visualization.DataTable();
                      data.addColumn('number', 'čas');
                      data.addColumn('number', 'teplota');

                      data.addRows([
                        [0,1],[1,2]
                      ]);

                      var options = {
                        'title':'How Much Pizza I Ate Last Night',
                        hAxis: {
                          title: 'Čas'
                        },
                        vAxis: {
                          title: 'Hodnota'
                        }
                      };
                      var chart = new google.charts.Line(document.getElementById('chart_mesicni'));
                      chart.draw(data, options);
                    }
                  }

                }

            }
        };
        //Graf mesicni 1 KONEC
        xmlhttp.open("GET","views/home/" + str + ".phtml",true);
        xmlhttp.send();
    }
  </script>
