<section class="horniPanel d-flex justify-content-between p-5">
  <div class="infobox AktualniTeplota p-5 text-center  col-xl-3 col-lg-3 col-md-12">
  <h1>Aktuální teplota: <?= $teplota[0] ?>&deg;C</h1>
  <h3><?= $teplota[1] ?></h3>
  </div>
  <div class="infobox AktualniTeplota p-5 text-center align-middle col-xl-5 col-lg-5 col-md-12">
    <div class="teplota">
      <h1>Aktuální teplota: <?= $teplota[0] ?>&deg;C</h1>
      <h3><?= $teplota[1] ?></h3>
    </div>
    <div class="row justify-content-center pt-5">
      <div class="vlhkost blueRow col-5 mx-1 align-middle">
        <h2>Vlhkost: <?= $Vlhkost['ABSVLHKOST'] ?>%</h1>
      </div>
      <div class="rosnybod redRow col-5">
        <h2>Rosný bod: <?= $Vlhkost['ROSNYBOD'] ?>&deg;C</h1>
      </div>
    </div>
  </div>
  <div class="infobox AktualniTeplota text-center col-xl-3 col-lg-3 col-md-12">
          <h3 class="p-1 blueRow">Statistiky</h3>
          <p class="statistika">Název čidla: <?= $jmenoCidla['JMENO'] ?></p>
          <p class="statistika">Počet měření: <?= $pocetMereni[0] ?></p>
          <p class="statistika">První měření: <?= $prvniMer[0] ?></p>
          <p class="statistika">Maximální teplota: <?= $maxTeplota['TEPLOTA'] ?>&deg;C</p>
          <p class="statistika">Minimální teplota: <?= $minTeplota['TEPLOTA'] ?>&deg;C</p>
  </div>
</section>

<article class="grafarna justify-content-center py-5">
  <div class="menuSmall">
    <ul class="nav nav-tabs">
      <li class="nav-item nav-item-smallMenu" onClick="loadTab('aktualne')" id="aktualneLi">
        <a class="nav-link active">Aktuálně</a>
      </li>
      <li class="nav-item nav-item-smallMenu" onClick="loadTab('dennisouhrn')" id="denniLi">
        <a class="nav-link">Denní souhrn</a>
      </li>
      <li class="nav-item nav-item-smallMenu" onClick="loadTab('mesicnisouhrn')" id="mesicniLi">
        <a class="nav-link">Měsíční souhrn</a>
      </li>
      <li class="nav-item nav-item-smallMenu" onClick="loadTab('rocnisouhrn')" id="rokyLi">
        <a class="nav-link">Roční souhrn</a>
      </li>
    </ul>
  </div>

  <section class="tabs p-5" id="aktualne">

  </section>

  <section class="tabs p-5" id="dennisouhrn">

  </section>

  <section class="tabs p-5" id="mesicnisouhrn">

  </section>

  <section class="tabs p-5" id="rocnisouhrn">

  </section>



</article>

<script type="text/javascript">
let loadingImage = '<p><img src="images/loading.gif"></p>';
function loadTab(tab) {
        console.log("kliknuto")
        if ($("#" + tab).html() != "") {
          console.log("tady")
            $("#" + tab).html(loadingImage);
            $.get("views/home/" + tab + ".phtml", function (data) {
                $("#" + tab).html(data);
            });
        }
    }
</script>
