<?php
session_start();
  $con =  ibase_connect("1.2.3.123:/var/lib/czf/jmnet.gdb", 'teplomer', 'remolpet');
  $id = $_SESSION['staniceID'];
  $prep = ibase_prepare("select distinct substr(datum,1,11) datum, min(teplota)MINTEMP,avg(teplota)AVGTEMP,max(teplota)MAXTEMP
                            from teplomer_data
                           where datum  > dateadd(-10 day to current_date)
                          and idcidlo = $id
                          group by datum
                          order by datum desc");
  $posledniDny = ibase_execute($prep);

  $prep1 = ibase_prepare("select distinct substr(datum,1,11) datum, min(rychlost)MINRYCHLOST,avg(rychlost)AVGRYCHLOST,max(rychlost)MAXRYCHLOST,
                          min(relvlhkost)MINVLHKOST,avg(relvlhkost)AVGVLHKOST,max(RELVLHKOST)MAXVLHKOST
                            from teplomer_data
                           where datum  > dateadd(-10 day to current_date)
                          and idcidlo = $id
                          group by datum
                          order by datum desc");
  $posledniDny1 = ibase_execute($prep1);

  $prep2 = ibase_prepare("select distinct substr(datum,1,11) datum, min(relvlhkost)MINVLHKOST,avg(relvlhkost)AVGVLHKOST,max(RELVLHKOST)MAXVLHKOST
                            from teplomer_data
                           where datum  > dateadd(-10 day to current_date)
                          and idcidlo = $id
                          group by datum
                          order by datum desc");
  $posledniDny2 = ibase_execute($prep2);

?>
<div class="dennisouhrn p-5">
<div class="charts p-3" style="background-color:#fff;" id="chart_denni"></div>
<div class="row justify-content-around">
  <div class="infobox posledniDny text-center col-5 mt-3 mx-auto" style="font-size:0.75em">
    <h4 class="blueRow p-2">Teplota za poslední dny</h4>
    <?php while($row = ibase_fetch_object($posledniDny)) : ?>
      <p class="statistika"><?= $row->DATUM ?> <span style="color:#425aa5;">Min.:</span> <?= $row->MINTEMP ?>°C <span style="color:#425aa5;">Průměr.:</span> <?= $row->AVGTEMP ?>°C <span style="color:#425aa5;">Max.:</span> <?= $row->MAXTEMP ?>°C</p>
    <?php endwhile ?>
  </div>
  <div class="infobox posledniDny text-center col-5 mt-3 mx-auto" style="font-size:0.75em">
    <h4 class="blueRow p-2">Ryhlost větru za poslední dny</h4>
    <?php while($row = ibase_fetch_object($posledniDny1)) : ?>
      <p class="statistika"><?= $row->DATUM ?> <span style="color:#425aa5;">Min.:</span> <?= $row->MINRYCHLOST ?>km/h <span style="color:#425aa5;">Průměr.:</span> <?= $row->AVGRYCHLOST ?>km/h <span style="color:#425aa5;">Max.:</span> <?= $row->MAXRYCHLOST ?>km/h</p>
    <?php endwhile ?>
  </div>
</div>

<div class="infobox posledniDny text-center col-8 mt-3 mx-auto" style="font-size:0.75em">
  <h4 class="blueRow p-2">Vlhkost za poslední dny</h4>
  <?php while($row = ibase_fetch_object($posledniDny2)) : ?>
    <p class="statistika"><?= $row->DATUM ?> <span style="color:#425aa5;">Min.:</span> <?= $row->MINVLHKOST ?>% <span style="color:#425aa5;">Průměr.:</span> <?= $row->AVGVLHKOST ?>% <span style="color:#425aa5;">Max.:</span> <?= $row->MAXVLHKOST ?>%</p>
  <?php endwhile ?>
</div>

</div>
