<?php

  session_start();
  $con =  ibase_connect("1.2.3.123:/var/lib/czf/jmnet.gdb", 'teplomer', 'remolpet');
  $id = $_SESSION['staniceID'];

  $prep = ibase_prepare("select substr(datum,1,4) ROKY, min(teplota) MINTEPLOTA, avg(teplota) AVGTEPLOTA, max(teplota) MAXTEPLOTA from TEPLOMER_DATA
                          where substr(datum,1,4) >= (select first 1 skip 0 distinct substr(datum,1,4)rok from
                          TEPLOMER_DATA
                          where idcidlo = 3710
                          order by rok asc)
                          and idcidlo = $id
                          group by ROKY;");
  $rocniTeplota = ibase_execute($prep);

  $prep = ibase_prepare("select substr(datum,1,4) ROKY, min(relvlhkost) MINVLHKOST, avg(relvlhkost) AVGVLHKOST, max(relvlhkost) MAXVLHKOST from TEPLOMER_DATA
                          where substr(datum,1,4) >= (select first 1 skip 0 distinct substr(datum,1,4)rok from
                          TEPLOMER_DATA
                          where idcidlo = 3710
                          order by rok asc)
                          and idcidlo = $id
                          group by ROKY;");
  $rocniVlhkost = ibase_execute($prep);

 ?>

<div class="rocnisouhrn p-5">

  <div class="row justify-content-around">

    <div class="infobox posledniDny text-center col-5 mt-3 mx-auto" style="font-size:0.75em">
      <h4 class="blueRow p-2">Souhrn teplot během let</h4>
      <?php while($row = ibase_fetch_object($rocniTeplota)) : ?>
        <p class="statistika"><?= $row->ROKY ?> <span style="color:#425aa5;">Min.:</span> <?= $row->MINTEPLOTA ?>°C <span style="color:#425aa5;">Průměr.:</span> <?= $row->AVGTEPLOTA ?>°C <span style="color:#425aa5;">Max.:</span> <?= $row->MAXTEPLOTA ?>°C</p>
      <?php endwhile ?>
    </div>

    <div class="infobox posledniDny text-center col-5 mt-3 mx-auto" style="font-size:0.75em">
      <h4 class="blueRow p-2">Souhrn vlhkostí během let</h4>
      <?php while($row = ibase_fetch_object($rocniVlhkost)) : ?>
        <p class="statistika"><?= $row->ROKY ?> <span style="color:#425aa5;">Min.:</span> <?= $row->MINVLHKOST ?>% <span style="color:#425aa5;">Průměr.:</span> <?= $row->AVGVLHKOST ?>% <span style="color:#425aa5;">Max.:</span> <?= $row->MAXVLHKOST ?>%</p>
      <?php endwhile ?>
    </div>

</div>
