<?php

  session_start();
  $con =  ibase_connect("1.2.3.123:/var/lib/czf/jmnet.gdb", 'teplomer', 'remolpet');
  $id = $_SESSION['staniceID'];

  $prep = ibase_prepare("select substr(datum,1,4) ROKY, min(teplota) MINTEPLOTA, avg(teplota) AVGTEPLOTA, max(teplota) MAXTEPLOTA from TEPLOMER_DATA
                          where substr(datum,1,4) >= (select first 1 skip 0 distinct substr(datum,1,4)rok from
                          TEPLOMER_DATA
                          where idcidlo = $id
                          order by rok asc)
                          and idcidlo = $id
                          group by ROKY;");
  $rocniTeplota = ibase_execute($prep);

  $prep1 = ibase_prepare("select substr(datum,1,4) ROKY, min(relvlhkost) MINVLHKOST, avg(relvlhkost) AVGVLHKOST, max(relvlhkost) MAXVLHKOST from TEPLOMER_DATA
                          where substr(datum,1,4) >= (select first 1 skip 0 distinct substr(datum,1,4)rok from
                          TEPLOMER_DATA
                          where idcidlo = $id
                          order by rok asc)
                          and idcidlo = $id
                          group by ROKY;");
  $rocniVlhkost = ibase_execute($prep1);

  $prep2 = ibase_prepare("select substr(datum,1,4) ROK, min(relvlhkost) MINHUM, avg(relvlhkost) AVGHUM, max(relvlhkost) MAXHUM,
                          min(teplota) MINTEMP, avg(teplota) AVGTEMP, max(teplota) MAXTEMP,
                          min(RYCHLOST) MINRYCHLOST, avg(RYCHLOST) AVGRYCHLOST, max(RYCHLOST) MAXRYCHLOST,
                          min(NARAZY) MINNARAZY, avg(NARAZY) AVGNARAZY, max(NARAZY) MAXNARAZY
                          from TEPLOMER_DATA
                          where substr(datum,1,4) >= (select first 1 skip 0 distinct substr(datum,1,4)rok from
                          TEPLOMER_DATA
                          where idcidlo = $id
                          order by rok asc)
                          and idcidlo = $id
                          group by ROK
                          order by rok desc;");
  $rocniSouhrn = ibase_execute($prep2);

 ?>

<div class="rocnisouhrn p-5">

  <div class="row justify-content-around">

    <div class="infobox posledniDny text-center col-5 mt-3" style="font-size:0.75em">
      <h4 class="blueRow p-2">Souhrn teplot během let</h4>
      <?php while($row = ibase_fetch_object($rocniTeplota)) : ?>
        <p class="statistika"><?= $row->ROKY ?> <span style="color:#425aa5;">Min.:</span> <?= $row->MINTEPLOTA ?>°C <span style="color:#425aa5;">Průměr.:</span> <?= $row->AVGTEPLOTA ?>°C <span style="color:#425aa5;">Max.:</span> <?= $row->MAXTEPLOTA ?>°C</p>
      <?php endwhile ?>
    </div>

    <div class="infobox posledniDny text-center col-5 mt-3" style="font-size:0.75em">
      <h4 class="blueRow p-2">Souhrn vlhkostí během let</h4>
      <?php while($row = ibase_fetch_object($rocniVlhkost)) : ?>
        <p class="statistika"><?= $row->ROKY ?> <span style="color:#425aa5;">Min.:</span> <?= $row->MINVLHKOST ?>% <span style="color:#425aa5;">Průměr.:</span> <?= $row->AVGVLHKOST ?>% <span style="color:#425aa5;">Max.:</span> <?= $row->MAXVLHKOST ?>%</p>
      <?php endwhile ?>
    </div>

</div>
<?php while($row = ibase_fetch_object($rocniSouhrn)) : ?>
  <div class="rokSo mt-3">
    <h1 style="color:#425aa5;"><?=$row->ROK?></h1>
    <hr>
    <div class="row justify-content-around py-3" style="font-size:0.7em;">
        <h3 class="col-6">Teplota</h3>
        <h3 class="col-6">Vlhkost</h3>
        <div class="teplotaData col-6">
          <h4><span style="color:#425aa5;">Min.: </span><?= $row->MINTEMP ?>°C | <span style="color:#425aa5;">Průměr.: </span><?= $row->AVGTEMP ?>°C | <span style="color:#425aa5;">Max.: </span><?= $row->MAXTEMP ?>°C</h4>
        </div>
        <div class="vlhkostData col-6">
          <h4><span style="color:#425aa5;">Min.: </span><?= $row->MINHUM ?>% | <span style="color:#425aa5;">Průměr.: </span><?= $row->AVGHUM ?>% | <span style="color:#425aa5;">Max.: </span><?= $row->MAXHUM ?>%</h4>
        </div>
        <h3 class="col-6">Rychlost větru</h3>
        <h3 class="col-6">Nárazová RV</h3>
      <div class="vitrData col-6">
        <h4><span style="color:#425aa5;">Min.: </span><?= $row->MINRYCHLOST ?>m/s | <span style="color:#425aa5;">Průměr.: </span><?= $row->AVGRYCHLOST ?>m/s | <span style="color:#425aa5;">Max.: </span><?= $row->MAXRYCHLOST ?>m/s</h4>
      </div>

        <div class="narazData col-6">
        <h4><span style="color:#425aa5;">Min.: </span><?= $row->MINNARAZY ?>m/s | <span style="color:#425aa5;">Průměr.: </span><?= $row->AVGNARAZY ?>m/s | <span style="color:#425aa5;">Max.: </span><?= $row->MAXNARAZY ?>m/s
        </h4></div>
    </div>
  </div>

<?php endwhile ?>


</div>
